apiVersion: v1
kind: ConfigMap
metadata:
  name: cyber-sentinel-config
  namespace: cyber-sentinel
data:
  MONGODB_URI: "mongodb://mongodb-svc:27017"
  REDIS_URL: "redis://redis-svc:6379/0"
  CELERY_RESULT_URL: "redis://redis-svc:6379/1"
  APP_REDIS_URL: "redis://redis-svc:6379/2"
  ZAP_API_URL: "http://zap-svc:8080"
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"
  ALLOW_PRIVATE_TARGETS: "true"
  WAZUH_API_URL: "https://10.4.89.178:55000"
  WAZUH_VERIFY_SSL: "false"
  FRONTEND_URL: "http://10.4.89.178"
  CORS_EXTRA_ORIGINS: "http://10.4.89.178,http://localhost:5173,http://localhost:3000"
  AI_PROVIDER: "groq"
