# ============================================================
# backend/domains/soc/tuning_models.py — Alert Tuning Recommendations
# ============================================================

from datetime import datetime, timezone
from typing import Literal, Optional

from beanie import Document
from pydantic import Field
from pymongo import ASCENDING, DESCENDING, IndexModel


class TuningRecommendation(Document):
    """
    Persisted tuning recommendation generated by the weekly TuningAnalyzer.

    One record per rule_id per analysis run (upserted daily).
    Admin reviews pending recs and marks them applied or dismissed.
    TTL index expires stale records after 90 days.
    """

    rule_id: str
    rule_description: str
    alert_count: int
    fp_count: int
    tp_count: int
    fp_rate: float                         # 0.0 – 1.0
    recommended_action: Literal[
        "increase_threshold",              # raise rule_level to reduce noise
        "add_exclusion",                   # add agent/IP exclusion in Wazuh
        "disable_rule",                    # rule is pure noise — disable it
    ]
    current_level: int
    suggested_level: Optional[int] = None # only set for increase_threshold
    top_agents: list[str] = []            # top agents generating FP alerts for this rule
    sample_alert_ids: list[str] = []      # up to 10 sample alert IDs for review
    reason: str = ""
    analysis_window_days: int = 7
    status: Literal["pending", "applied", "dismissed"] = "pending"
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    applied_at: Optional[datetime] = None
    applied_by: Optional[str] = None      # user_id of admin who acted on it

    class Settings:
        name = "tuning_recommendations"
        indexes = [
            IndexModel([("rule_id", ASCENDING)]),
            IndexModel([("generated_at", DESCENDING)]),
            IndexModel([("status", ASCENDING)]),
            IndexModel([("recommended_action", ASCENDING)]),
            IndexModel([("fp_rate", DESCENDING)]),
            # TTL — expire recommendations after 90 days
            IndexModel([("generated_at", ASCENDING)], expireAfterSeconds=7_776_000),
        ]
