apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: cyber-sentinel
spec:
  clusterIP: None   # headless — enables StatefulSet DNS (mongodb-svc:27017)
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
