apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: cyber-sentinel
spec:
  clusterIP: None   # headless — enables StatefulSet DNS (redis-svc:6379)
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
