apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cyber-sentinel

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - celery-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cyber-sentinel
  app.kubernetes.io/managed-by: kustomize
